// r2Service.js
// Cloudflare R2 is S3-compatible — we use @aws-sdk/client-s3 directly from the browser
// via presigned URLs generated by a lightweight proxy, OR directly if CORS is configured.
// 
// For this app, we use the S3Client with:
//   endpoint : https://<ACCOUNT_ID>.r2.cloudflarestorage.com
//   region   : "auto"
//   credentials: { accessKeyId, secretAccessKey }
//
// ⚠️  SECURITY NOTE: These credentials are stored in localStorage and used directly
//     from the browser. Fine for private internal tools; for public apps use a backend.

import { S3Client, ListObjectsV2Command, GetObjectCommand, PutObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

let _client = null;
let _bucket = null;

export function initR2(config) {
  _bucket = config.bucket;
  _client = new S3Client({
    region: 'auto',
    endpoint: `https://${config.accountId}.r2.cloudflarestorage.com`,
    credentials: {
      accessKeyId:     config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
    },
    forcePathStyle: true,  // required for R2 presigned URLs
  });
}

export function isInitialized() {
  return !!_client;
}

export function getClient() { return _client; }
export function getBucket()  { return _bucket; }

export async function listVideos() {
  if (!_client) throw new Error('R2 not configured');
  const cmd = new ListObjectsV2Command({ Bucket: _bucket });
  const res = await _client.send(cmd);
  const items = (res.Contents || []).filter(obj =>
    /\.(mp4|mov|mkv|webm|avi|m4v|flv|wmv)$/i.test(obj.Key)
  );
  return items.map(obj => ({
    key:          obj.Key,
    size:         obj.Size,
    lastModified: obj.LastModified,
  }));
}

export async function getDownloadUrl(key, expiresIn = 3600) {
  if (!_client) throw new Error('R2 not configured');
  const cmd = new GetObjectCommand({ Bucket: _bucket, Key: key });
  return getSignedUrl(_client, cmd, { expiresIn });
}

export async function uploadVideo(file, onProgress) {
  if (!_client) throw new Error('R2 not configured');

  // For multipart / progress we use fetch + presigned PUT URL
  const putCmd = new PutObjectCommand({
    Bucket: _bucket,
    Key:    file.name,
    ContentType: file.type,
  });
  const signedUrl = await getSignedUrl(_client, putCmd, { expiresIn: 3600 });

  await new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('PUT', signedUrl, true);
    xhr.setRequestHeader('Content-Type', file.type);
    xhr.upload.onprogress = e => {
      if (e.lengthComputable && onProgress) onProgress(Math.round((e.loaded / e.total) * 100));
    };
    xhr.onload  = () => (xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(new Error(`Upload failed: ${xhr.status}`)));
    xhr.onerror = () => reject(new Error('Upload network error'));
    xhr.send(file);
  });

  return file.name;
}

export async function deleteVideo(key) {
  if (!_client) throw new Error('R2 not configured');
  const cmd = new DeleteObjectCommand({ Bucket: _bucket, Key: key });
  await _client.send(cmd);
}

export function formatBytes(bytes, decimals = 2) {
  if (!bytes) return '0 B';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
}

export function formatDate(date) {
  if (!date) return '—';
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric',
  });
}
